version: "3"


services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    network_mode: "bridge"
 #   networks:
 #     - local
    environment:
        VIRTUAL_HOST: {virtual-host}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data

